name: Build and push to ECR

on:
  push:
    branches: [main]

env:
  AWS_REGION: ${{secrets.AWS_REGION}}
  ECR_REPOSITORY: gstream/nuxt

jobs:
  build:
    runs-on: ubuntu-latest
    environment: UAT
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_REGION}} 

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag and push Nuxt image
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:uat .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:uat
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:uat" >> $GITHUB_OUTPUT
